=head1 FEC PARSER

Converting political contribution data from the FEC(fec.gov)'s COBOL format to CSV for loading into MySQL.

=head2 VERSION

version 0.1a (DEPRECIATED)

=head2 SYNOPSIS

FEC Data is in a stupid format. This converts it into normalized CSV files for upload in MySQL.

=head2 WINDOWS

For them there Winderrrz users who like GUIs: https://sourceforge.net/projects/fectool/

=head2 INSTALLATION

1) Download the necessary files via git clone.

2) Change a lot of the absolute file paths.

*NOTE: Very quickly written a long while back, YMMV.

=head2 DEPENDENCIES
open
All should be available with Perl or CPAN.

Must load Archive::Extract

=head2 SUPPORT AND DOCUMENTATION

No support since it's depreciated. Considering using OpenData (http://www.opensecrets.org/action/data.php).

=head2 COPYRIGHT AND LICENCE

Copyright (C) 2007,2008 Naveen Manivannan (Nash Research Group)

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.
