=head1 FEC PARSER

Converting political contribution data from the FEC(fec.gov) COBOL format to CSV for loading into MySQL.

=head2 VERSION

version 0.1a (DEPRECATED).

=head2 SYNOPSIS

FEC Data is in a stupid format. This converts it into normalized CSV files for upload in MySQL.
L<<a href="http://www.fec.gov/finance/disclosure/ftpdet.shtml">Detailed Files About Candidates, Parties and Other Committees</a>>

=head2 WINDOWS

For them there Windows users who like GUIs: https://sourceforge.net/projects/fectool/

=head2 INSTALLATION

1) Download the necessary files via git clone.

2) Change a lot of the absolute file paths.

*NOTE: Very quickly written a long while back, YMMV.
**NOTE: Currently started new project to parse .fec files vs COBOL file!

=head2 DEPENDENCIES

Must load Archive::Extract

=head2 LIMITATIONS

The COBOL file turncates long names.

=head2 SUPPORT AND DOCUMENTATION

No support since it's depreciated. Considering using OpenData (http://www.opensecrets.org/action/data.php).

=head2 COPYRIGHT AND LICENCE

Copyright (C) 2007,2008 Naveen Manivannan (Nash Research Group)

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.
